# Generated by Django 5.0 on 2023-12-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogapp", "0002_blogpost_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=models.TextField(default="Write your content here..."),
        ),
    ]
